repository:
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Vercel (Production)
      enforce_admins: true
      required_pull_request_reviews:
        require_code_owner_reviews: true
        required_approving_review_count: 1
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false


