name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ ci/* ]

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm install --ignore-scripts --legacy-peer-deps
      - name: Typecheck root
        run: npx tsc -p tsconfig.json --noEmit || true
      - name: Lint
        run: npm run lint || true
      - name: Build adapters package (if present)
        run: npm run build -w @lovable/expertfolio-adapters || true
      - name: Build shared package (if present)
        run: npm run build -w @lovable/shared || true

